name: Continuous integration and deploment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: window-latest
    steps: 
      - name: Check out code
         uses: actions/checkout@v3

        -name: Setup .Net 5
          uses: actions/setup-dotnet@v3
          with:
          dotnet-version: '5.0.x'

        -name: Restore Dependencies
          run: dotnet Restore

        -name: build app
        run: dotnet build -c Release --no-restore